rethinkdb:
  image: rethinkdb
  volumes:
    - ${PWD}/data:/data
  ports:
    - 8081:8080
    - 28015:28015
    - 29015:29015

boot-app:
  build: .
  links:
    - rethinkdb:rethinkdb
  ports:
    - 8080:8080